dependencies:
  - name: postgresql
    version: "2"
    repository: "alias:stable"
    condition: postgresql.enabled

  - name: postgresql
    version: "2"
    repository: "alias:stable"
    condition: anchore-feeds-db.enabled,anchoreEnterpriseGlobal.enabled
    alias: anchore-feeds-db

  - name: redis
    version: "10"
    repository: "alias:stable"
    condition: anchore-ui-redis.enabled,anchoreEnterpriseGlobal.enabled
    alias: anchore-ui-redis
